# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cole Cecil
description: > # this means to ignore newlines until "baseurl:"
  I'm Cole. I develop software for a living, and I also do it for fun in my free
  time. I write here about my personal projects, as well as creating tutorials
  to share the things I've learned.
twitter_username: colejcecil

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colececil.io" # the base hostname & protocol for your site
paginate: 5
permalink: /blog/:year/:title/

# Build settings
exclude: ["working-files"]
markdown: kramdown
highligher: rouge
timezone: America/Central

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Plugins
gems: ['jekyll-paginate']
