name: Build & Deploy
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        id: checkoutRepo
        uses: actions/checkout@v4.2.2
      - name: Build static content
        id: buildStaticContent
        uses: dagger/dagger-for-github@v7.0.6
        with:
          version: '0.15.3'
          verb: call
          args: build export --path=./dist
      - name: Upload static content
        id: uploadStaticContent
        if: ${{github.ref == 'refs/heads/master'}}
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist
  deploy:
    name: Deploy
    if: ${{github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployStaticContent.outputs.pages_url}}
    concurrency: github-pages
    steps:
      - name: Deploy static content to GitHub Pages
        id: deployStaticContent
        uses: actions/deploy-pages@v4.0.5
